---
permalink: concept_preconfiguration_task_overview.html
sidebar: sidebar
keywords: 
summary: 'Before using SMI-S Provider for the first time, you must validate your preliminary configuration.'
---
= Preconfiguration validation
:icons: font
:imagesdir: ./media/

[.lead]
Before using SMI-S Provider for the first time, you must validate your preliminary configuration.

Perform the following tasks before using SMI-S Provider:

. From NetApp SMI-S Provider, verify that the CIM server is started.
. Add a CIM server user.
. Verify management of the storage system by adding at least one storage system for SMI-S Provider.
. (Optional) Generate a self-signed certificate for the CIMOM.

By default, authentication is enabled for SMI-S Provider.

After you have successfully performed this validation, you can begin to manage your storage systems using NetApp SMI-S Provider.

*Related information*

xref:task_verifying_the_cim_server_status.adoc[Verifying the CIM server status]

xref:task_adding_cim_server_users.adoc[Adding a CIM server user]

xref:task_verifying_that_the_storage_system_is_working_correctly.adoc[Verifying that the storage system is working correctly]

xref:task_generating_a_self_signed_certificate_for_the_cim_server_windows.adoc[Generating a self-signed certificate for the CIM server]

xref:task_enabling_or_disabling_authentication_for_smi_s_provider.adoc[Enabling or disabling authentication for NetApp SMI-S Provider]
