---
permalink: reference-entering-passwords-containing-special-characters.html
sidebar: sidebar
keywords: troubleshooting, issue, encounter
summary: "Issues encountered with NetApp SMI-S Provider."
---
= Issue entering passwords containing special characters
:icons: font
:imagesdir: ./media/

* *Issue*
+
In English-language operating systems, using a password that contains special characters with the `smis` command does not work in a Windows environment. This issue has not been tested with non-English operating systems.

* *Cause*
+
In Windows, the following characters, plus any spaces, are considered special characters and cause password input to fail if the password is not enclosed in quotation marks:
+
, & ' < > ; | = {caret} "

* *Corrective action*
+
If a password contains spaces or special characters, enclose it in double quotes (" ") when you use it in the `smis` command. Note that the quote character (") is a special character and should never be used in your password.

== Issuing passwords with special characters

`smis add 1.2.3.4 Administrator "pass word"`

`smis add 1.2.3.4 Administrator "pass&word"`
