---
permalink: reference-possible-errors-when-loading-shared-libraries.html
sidebar: sidebar
keywords: troubleshooting, issue, encounter
summary: "Issues encountered with NetApp SMI-S Provider."
---
= Possible errors while loading shared libraries
:icons: font
:imagesdir: ./media/

[.lead]
* *Messages*
+
`Error while loading shared libraries: libssl.so 1.0.0: cannot open shared object file: No such file or directory.`
+
The `smis cimserver` status shows the cimserver is running properly, but all other `/usr/netapp/smis/pegasus/bin/cim` commands show various failure messages.
+
For example, you might receive the message `cimserver not running` when executing the `cimserver`, or you might receive the message `/usr/netapp/smis/pegasus/bin/ cimcli: symbol lookup error: /usr/netapp/smis/pegasus/bin/cimcli: undefined symbol: _ZN7Pegasus16StringConversion21decimalStringToUint64EPKcRy` when executing cimcli. These examples are not all-inclusive.

* *Description*
+
This message (and similar messages) occur when the `LD_LIBRARY_PATH` environment is not set to the installation directory.

* *Corrective action*
+
Enter one of the following commands to set the `LD_LIBRARY_PATH` environment variable to the installation directory:

`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/netapp/smis/pegasus/lib`

`setenv LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/netapp/smis/pegasus/lib`
