---
permalink: reference_cannot_connect_to_localhost_5989_error.html
sidebar: sidebar
keywords: 
summary: ''
---
= Cannot connect to localhost:5989
:icons: font
:imagesdir: ./media/

* *Message*
+
`Cannot connect to localhost:5989. Connection failed. Trying to connect to localhost:5989`

* *Description*
+
This message occurs when HTTPS connections are disabled or the HTTPS port is not set to 5989, or if the provider has stopped working and remains in a hanging state.

* *Corrective action*
+
Verify that the values of `enableHttpsConnection` and `httpsPort` are correct:
+
`cimconfig -g enableHttpsConnection`
+
`cimconfig -g httpsPort`
+
If `enableHttpsConnection` is not set to "`true`", enter the following commands:
+
`cimconfig -s enableHttpsConnection -p`
+
`smis cimserver restart`
+
If `httpsPort` is not set to 5989, enter the following commands:
+
`cimconfig -s httpsPort=5989 -p`
+
`smis cimserver restart`
+
If the provider has stopped working and remains in a hanging state, open Task Manager and end the process, and then restart the provider.
