---
permalink: reference-warning-26130.html
sidebar: sidebar
keywords: troubleshooting, issue, encounter
summary: "Issues encountered with NetApp SMI-S Provider."
---
= Warning 26130
:icons: font
:imagesdir: ./media/

[.lead]
Warning 26130 occurs when storage capacity is allocated to a host group in which none of the hosts have access to the storage array, preventing you from placing virtual machines on the storage system. Learn how to grant the required access and resolve the warning.

== Message

`Warning (26130) Storage pool has been allocated to host group where none of hosts in host group has access to storage array.`

== Description

This error occurs when you allocate storage capacity and grant an array access to hosts that are in a host group. With this warning, it is impossible to put virtual machines on the storage systems.

== Corrective action

. On each host machine, add the IP address of each storage system to the iSCSI Initiator application.
. If required, on each storage system, for each host machine, create one unique igroup linked with the proper iSCSI node name from the corresponding host machine.
. For each host machine connected to ONTAP, open the MPIO application and add the following hardware ID:
 ** For ONTAP, enter `*NETAPP LUN C-Mode*`.
. Reboot the host machines.
. Remove the provider.
. Set the storage pool again.
// 2024-10-15, jira OTHERDOC86