---
permalink: reference-hostagentaccessdenied-error-id-26263.html
sidebar: sidebar
keywords: troubleshooting, issue, encounter
summary: "Issues encountered with NetApp SMI-S Provider."
---
= HostAgentAccessDenied (ID: 26263)
:icons: font
:imagesdir: ./media/

[.lead]
The `HostAgentAccessDenied` error (ID: 26263) occurs when System Center Virtual Machine Manager (SCVMM) attempts to connect to NetApp SMI-S Provider using a user account that is not part of the SMI-S Provider trust store. Learn why this error occurs and how to add a valid CIM user to resolve it.

== Message

`Registration of storage provider _smis_provider_machine_ for user _name_ failed from _SCVMM__ _(machine)_ with error code HostAgentAccessDenied. Specify valid provider, port and user credentials for storage discovery. ID: 26263`

== Description

This message occurs when a user is specified in SCVMM to connect to SMI-S Provider but is not part of the SMIS trust store.

To enable communication between SCVMM and SMI-S Provider, a valid CIM user (Local Administrator user or Domain user of the Local Administrators group) must be added to the SMIS trust store using the `cimuser` command.

== Corrective action

Add the Local Administrator user (on the SMI-S Provider machine) to the CIM server database using the `cimuser` command: `cimuser -a -u _admin user_ -w _password_`. You must then use that administrative user when adding NetApp SMI-S Provider to SCVMM.

If the domain controller takes too long to authenticate the Domain user, you must use the Local Administrator user on the SMI-S Provider machine.

If the error persists, you can disable authentication in SMI-S Provider.
