---
permalink: reference-cimuser-command-options.html
sidebar: sidebar
keywords: cimuser, options, add, remove, modify, list, cim server
summary: "You can use the cimuser options to add, remove, modify, and list CIM server users."
---
= cimuser
:icons: font
:imagesdir: ./media/

[.lead]
You can use the `cimuser` command to add, remove, delete, modify, and list CIM server users, as well as manage their passwords.

.Syntax

`cimuser _options_`

.Location

`C:\Program Files (x86)\NetApp\smis\pegasus\bin`

.Privilege level

Administrator (Windows)

== Options

* *-a*
+
Adds a CIM user.

* *-h, --help*
+
Displays help for the `cimuser` command.

* *-l*
+
Lists CIM users.

* *-m*
+
Modifies a CIM user's password. The password can be between 4 through 32 characters long.

* *-n*
+
Creates a new password for the specified user. The password can be between 4 through 32 characters long.

* *-r*
+
Removes a specified CIM user.

* *-u*
+
Specifies a CIM user name.

* *--version*
+
Displays the version of the CIM server.

* *-w*
+
Specifies the password for the specified user.

== Example

Create a CIM user named sydney with a password of password1:

----
cimuser -a -u sydney -w password1
User added successfully.
----
