---
permalink: reference_types_of_cim_users_and_associated_operations.html
sidebar: sidebar
keywords: smi-s provider, various types, control, access
summary: "When using SMI-S Provider, there are various types of user that you can assign to a user to control their access to the CIM server."
---
= Types of CIM users and associated operations
:icons: font
:imagesdir: ./media/

[.lead]
When using SMI-S Provider, there are various types of user that you can assign to a user to control their access to the CIM server.

Starting with this release, the Domain user is allowed to modify the SMI-S Provider user database and other configuration settings as a Domain user of the Local Administrators group.

The following table lists the supported users of the CIM server and the operations that each type can perform.

[cols="2*",options="header"]
|===
|Type of user| Operations
a|
Domain administrator of the Administrators group
.5+a|
SMI-S Provider configuration and user management using `cimconfig` and `cimuser` commands. For example:

* Add or remove a user to or from the trust store of SMI-S Provider.
* Enable, disable, or change the log level and tracing configuration.
* Enable or disable the authentication engine in SMI-S Provider.

Storage management and verification using `smis` and `cimcli` commands. For example:

* Add or remove storage controllers or SVMs to or from a SMI-S Provider repository or database or cache.
* Refresh storage controllers or SVMs in SMI-S Provider cache.
* Verify storage controller or SVM management.

SCVMM discovery operations using the SCVMM GUI.
a|
Domain user of the Local Administrators group
a|
Local user of the Local Administrators group
a|
Built-in Domain Administrator user
a|
Built-in Local Administrator user
a|
Domain user of the Users group
.2+a|
SCVMM discovery operations using the SCVMM GUI.
a|
Local user of the Users group
|===

[NOTE]
====
If you have SMI-S Provider on a Windows host and changed any "`Administrator`" user name, you must log out of the system and then log back in. The SMI-S Windows Service inherits authentication during this time; as a result, any change to the credentials are not recognized until the administrator logs out and then logs in again.
====
