---
permalink: reference-trace-setting-values.html
sidebar: sidebar
keywords: specify, comments, trace, target, change, location
summary: "You can specify the components to trace, the trace target, and the level of tracing. Optionally, you can change the name and location of the trace file if you do not want to use the default trace file name and location."
---
= Trace setting values
:icons: font
:imagesdir: ./media/

[.lead]
You can specify the components to trace, the trace target, and the level of tracing. Optionally, you can change the name and location of the trace file if you do not want to use the default trace file name and location.

You can configure the following trace settings:

* *traceComponents*
+
Specifies the components to be traced. By default, all components are traced.

* *traceFacility*
+
Specifies the target to which trace messages are written:

 ** File
+
This is the default value, which specifies that trace messages are written to the file specified by the traceFilePath configuration option.

 ** Log
+
Specifies that trace messages are written to the cimserver_standard log file.

* *traceFilePath*
+
Specifies the location of the trace file. By default, the trace is file is named `cimserver.trc` and is located in the `traces` directory.

* *traceLevel*
+
Specifies the level of tracing. By default, tracing is disabled.
+

[cols="2*",options="header"]
|===
| Trace level| Trace messages written
a|
0
a|
Tracing is disabled.
a|
1
a|
Severe and log messages.
a|
2
a|
Basic flow trace messages (low data detail)
a|
3
a|
Inter-function logic flow (medium data detail)
a|
4
a|
High data detail
a|
5
a|
High data detail + Method enter and exit
|===
