---
permalink: reference-smi-s-agent-sizing-and-performance-information.html
sidebar: sidebar
keywords: maximum, systems, netapp smi-s provider, help, understand, performance, capability
summary: "Knowing the maximum number of systems managed by NetApp SMI-S Provider helps you understand its performance capabilities."
---
= NetApp SMI-S Provider sizing and performance
:icons: font
:imagesdir: ./media/

[.lead]
Knowing the maximum number of systems managed by NetApp SMI-S Provider helps you understand its performance capabilities.

*Sizing*

NetApp SMI-S Provider can manage up to the following numbers of objects in ONTAP:

* 30 storage virtual machines (SVMs) 
* 100 SVMs (without indications)
* 10 SVMs (with indications)
* 1,500 LUNs (per FlexVol volume)
* 200 CIFS file shares (per FlexVol volume)

If the FlexVol contains both qtrees and volumes, the qtrees appear as directories. You should be careful to not delete the qtrees accidentally when deleting volumes.

*Performance notice*

For configurations with 5,000 FlexVol volumes or 300,000 Snapshot copies, you might experience performance issues with the following `cimcli` commands:

* `cimcli ei ONTAP_Snapshot -n root/ontap`
* `cimcli ei ONTAP_SnapshotBasedOnFlexVol -n root/ontap`
* `cimcli ei ONTAP_StorageVolumeStats -n root/ontap`

The Interoperability Matrix Tool (IMT) contains the latest information about sizing and performance.
// 2024-10-15, jira OTHERDOC86