---
permalink: reference-smi-s-agent-takes-a-long-time-to-start.html
sidebar: sidebar
keywords: netapp smi-s provider
summary: "Issues encountered with NetApp SMI-S Provider."
---
= NetApp SMI-S Provider takes a long time to start
:icons: font
:imagesdir: ./media/

[.lead]
NetApp SMI-S Provider can take up to 15 minutes to start on Windows systems with storage systems already under management, because the `smis cimserver` command waits for the provider local cache to populate. Learn what to expect when starting the provider and why the `smis cimserver` command is the recommended method.

* *Description*
+
On Windows systems, with storage systems that are already under management, when you start NetApp SMI-S Provider using the `smis cimserver` command, the command does not return until the provider local cache is populated. It waits a maximum of 15 minutes while the cache is populated, and you cannot use NetApp SMI-S Provider until it returns.
+
Using the `smis cimserver` command is the recommended method of starting NetApp SMI-S Provider.
