---
permalink: reference-smis-addsecure.html
sidebar: sidebar
keywords: smis, addsecure, command, https connection configuration, manage, monitor
summary: "The smis addsecure command adds a storage system with an HTTPS connection to your configuration to enable you to manage and monitor the device. Unless is it necessary, you should use smis addsecure instead of smis add."
---
= smis addsecure
:icons: font
:imagesdir: ./media/

[.lead]
The `smis addsecure` command adds a storage system with an HTTPS connection to your configuration to enable you to manage and monitor the device. Unless is it necessary, you should use `smis addsecure` instead of `smis add`.

== Syntax

`smis addsecure`

`_storage_sys storage_sys_user_`
 +
 `[-t {*http* | *https*}]`


[NOTE]
====
Operating systems using languages other than U.S. English cannot use the `addsecure` command.
====

== Location

`C:\Program Files (x86)\NetApp\smis\pegasus\bin`

== Privilege level

Administrator (Windows)

== Parameters

* `*_storage_sys_*`
+
Name or IP address of the storage system that you are adding
+
If you are specifying the IP address, you can use IPv4 or IPv6. Both compressed and full IPv6 addressees are supported, for example `1001:0002:0000:0000:0000:0000:0003:0004` or `1001:2::3:4`.

* `*_storage_sys_user_*`
+
User name of the administrator who manages the storage system that you are adding

* `*_storage_sys_pwd_*`
+
Optional: password of the administrator who manages the storage system that you are adding
+
As a best practice, do not use this parameter for security reasons. This parameter is provided only for automation and backward compatibility.

* `*[-t {http | https}]*`
+
Protocol to be used: HTTPS (default) or HTTP

== Storage system-agent and agent-client protocol

The `smis add` and `smis addsecure` commands determine the protocol used between the storage system and the provider. The `[-t {*http* | *https*}]` parameter determines the protocol used between the provider and the client.

The `smis addsecure` command and the `[-t {*https*}]` parameter connects using SSL encryption, and unencrypted traffic is not allowed. The `smis add` command and the `[-t {*http*}]` parameter connects without using SSL encryption, and unencrypted traffic is allowed.

You should consider your environment's security needs before disabling SSL-encrypted connections.

== Example

Add a storage system using IPv4 with an IP address of 10.32.1.4 over HTTPS:

----
smis addsecure 10.32.1.4 user2 password2
----

A confirmation message appears that the storage system was successfully added. If an error occurred, an error message appears.

== Example

Add a storage system using IPv6 over HTTPS:

----
smis addsecure 1001:0002:0000:0000:0000:0000:0003:0004 user2 password2
smis addsecure 1001:2::3:4 user2 password2
----

A confirmation message appears that the storage system was successfully added. If an error occurred, an error message appears.

== Example

Add a storage system with an IP address of 10.32.1.4 over HTTPS on a non-English-language system:

----
cimcli -n root/ontap ci ontap_filerdata hostname="10.32.1.4" username="vsadmin" password="PasSw0Rd" port=443 comMechanism="HTTPS" --timeout 180
----
