---
permalink: reference-supported-operating-systems.html
sidebar: sidebar
keywords: installing, smi-s provider, verify, windows, host, operating systems
summary: "Before installing SMI-S Provider, you must verify that the Windows host is running a supported operating system."
---
= Supported operating system versions
:icons: font
:imagesdir: ./media/
:pp: {plus}{plus}

[.lead]
We recommend you install SMI-S Provider on its own dedicated Windows virtual machine (VM). This VM can be on the same domain to allow for secure and convenient management.

Before installing SMI-S Provider, you must verify that the Windows host is running a supported operating system.

[cols="3*",options="header"]
|===
| Operating system| Supported versions| Required client software
a|
Windows
a|

* Microsoft Windows Server 2025
* Microsoft Windows Server 2022
* Microsoft Windows Server 2019
* Microsoft Windows Server 2016

a|
The Microsoft Visual C{pp} 2010 runtime libraries are automatically installed during the SMI-S Provider installation. To avoid potential issues related to runtime libraries, you must install Microsoft Visual C{pp} 2010 Redistributable Package (x86) from the following location: http://www.microsoft.com
|===

== Ensure the provider host machine meets the specifications

To run SMI-S Provider, the provider host machine must meet the following specifications:

* The provider host machine cannot be used to host a Hyper-V node.
* The System Center Virtual Machine Manager (SCVMM) must not be running on the provider host machine.
* The provider host machine must not run other programs that are memory-intensive.
* The provider host machine must not run SMI-S Providers from any other vendor.

// 2025-03-27, jira OTHERDOC114
// 2025-12-12, jira OTHERDOC 173 naadia
