---
permalink: reference_handling_smi_s_agent_crashes_in_windows.html
sidebar: sidebar
keywords: troubleshooting, issue, encounter
summary: "Issues encountered with NetApp SMI-S Provider."
---
= SMI-S Provider crashes in Windows
:icons: font
:imagesdir: ./media/

* *Issue*
+
SMI-S Provider crashes in Windows.

* *Cause*
+
This issue occurs for a variety of reasons, documented in files generated at the time of the crash.

* *Corrective action*
+
Restart the provider and send the following information to technical support for further analysis:

 ** Dump file from the `C:\Program Files (x86)\NetApp\smis\pegasus\pegasus\logs` directory
 ** Log files from the `C:\Program Files (x86)\NetApp\smis\pegasus\pegasus\logs` directory
 ** Trace files from the `C:\Program Files (x86)\NetApp\smis\pegasus\pegasus\traces` directory
+
Messages similar to the following also appear in the trace file:
+
`23-May-2013 20:46:36.874 INFO cimserver: createMiniDump: SMI-S Agent has crashed, attempting to generate a dump file`
+
`23-May-2013 20:46:37.14 INFO cimserver: createMiniDump: Process dumped to C:\Program Files (x86)\netapp\smis\pegasus\logs\SMI-S Agent-8be55da-2011_05_23-20_46_36.dmp`

 ** The files `version.txt` and `cimserver_current.conf` from the `C:\Program Files (x86)\NetApp\smis\pegasus\pegasus` directory
