---
permalink: task_manage_cim_server_users.html
sidebar: sidebar
keywords: smi-s provider, add, remove, remove, cim users, authorized, cim server, cim user, password, modify
summary: "You can use SMI-S Provider to add and remove CIM users that are authorized to use the CIM server. You can also list all current CIM users and modify their passwords."
---
= Manage CIM server users
:icons: font
:imagesdir: ./media/

[.lead]
You can use SMI-S Provider to add and remove CIM users that are authorized to use the CIM server. You can also list all current CIM users and modify their passwords.

== Before you begin

* You must already have login credentials as Administrator.
* You must already have logged in to the host system as Administrator.

== Steps

. Access NetApp SMI-S Provider.
. Create a local user account.
. Add the user to the Administrators group.
+
For more information, see _System documentation_.

. Complete one of the following actions:
+
[cols="3*",options="header"]
|===
| Action| Command| Additional information
a|
Add a CIM server user
a|
`*cimuser -a -u _user_name_*`
a|
After entering the command, enter and reenter the password when prompted.
a|
List the current users authorized to use the CIM server
a|
`*cimuser -l*`
a|
NA
a|
Change the password for a CIM server user
a|
`*cimuser -m -u _user_name_*`
a|
After entering the command, enter and reenter the new and old password when prompted.
a|
Remove a CIM server user not authorized to use the CIM server
a|
`*cimuser -r -u _user_name_*`
a|
NA
|===
