---
permalink: task_specifying_the_maximum_number_of_threads_per_message_service_queue.html
sidebar: sidebar
keywords: default, smi-s provider, 80 threads, per message, service queue, machine performance
summary: "By default, SMI-S Provider allows 80 threads per message service queue. You can specify the maximum thread value as 1 through 5000. Increasing the maximum number of threads can impact the SMI-S Provider machine’s performance, so carefully consider whether you need to increase this value."
---
= Specifying the maximum number of threads per message service queue
:icons: font
:imagesdir: ./media/

[.lead]
By default, SMI-S Provider allows 80 threads per message service queue. You can specify the maximum thread value as 1 through 5000. Increasing the maximum number of threads can impact the SMI-S Provider machine's performance, so carefully consider whether you need to increase this value.

== What you'll need

* You must already have login credentials as Administrator.
* You must already have logged in to the host system as Administrator.

== About this task

If your trace file shows many lines of `insufficient resources` output, you must increase the number of threads in increments of 500.

If you set the maximum number of threads to fewer than 20, using the `*cimcli -n root/ontap niall*` command, the provider becomes unresponsive and returns the `Insufficient threadpool` message in the trace file. If this occurs, you must increase the number of threads in increments of 500 and then restart the provider.

== Steps

. Access NetApp SMI-S Provider.
. Create a system or user environment variable named `PEGASUS_MAX_THREADS_PER_SVC_QUEUE` with the new maximum thread value.
+
For information about creating environment variables, see your Windows documentation.

. Restart the CIM server:
+
`*smis cimserver restart*`
