---
permalink: task-enable-indications-in-smi-s-agent.html
sidebar: sidebar
keywords: netApp smi-s provider, lifecycle, disable, default, indication
summary: "Alert, FileSystem Quota, and Lifecycle indications are disabled by default. You can enable these indications by setting the environment variable PEGASUS_DISABLE_INDICATIONS to false."
---
= Enable indications in SMI-S Provider
:icons: font
:imagesdir: ./media/

[.lead]
Alert, FileSystem Quota, and Lifecycle indications are disabled by default. You can enable these indications by setting the environment variable `PEGASUS_DISABLE_INDICATIONS` to `false`.

== Before you begin

* You must already have login credentials as Administrator.
* You must already have logged in to the host system as Administrator.

== About this task

When `PEGASUS_DISABLE_INDICATIONS` is set to `false`, then Alert (`ONTAP_AlertIndication`), FileSystem Quota (`ONTAP_FSQuotaIndication`), and Lifecycle indications are enabled on NetApp SMI-S Provider.

== Steps

. Access NetApp SMI-S Provider.
. Set the `PEGASUS_DISABLE_INDICATIONS` environment variable to `false`.
. Restart the CIM server:
+
`*smis cimserver restart*`
