---
permalink: task_manage_storage_systems.html
sidebar: sidebar
keywords: smis-provider, commands, add, delete, list, storage, systems, cimom repository
summary: "You can use NetApp SMI-S Provider commands to add, delete, and list storage systems in the CIMOM repository. You can also list NFS and CIFS exports and exported LUNs for storage systems."
---
= Manage storage systems
:icons: font
:imagesdir: ./media/

[.lead]
You can use NetApp SMI-S Provider commands to add, delete, and list storage systems in the CIMOM repository. You can also list NFS and CIFS exports and exported LUNs for storage systems.

== Before you begin

* You must already have login credentials as Administrator.
* You must already have logged in to the host system as Administrator.

== About this task

For ONTAP, you must specify a management IP address for an SVM, not a cluster IP address, and you must provide the credentials for a vsadmin user. SMI-S Provider does not support cluster IP addresses or node management IP addresses, nor does it support node admin or node SVMs.

[NOTE]
====
You should set the data protocol value to `none` for the management LIF when you add it to the SMI-S Provider.
====

== Steps

. Access NetApp SMI-S Provider.
. Complete one of the following actions:
+
[cols="3*",options="header"]
|===
| Action| Command| Additional information
a|
Add a storage system with an HTTP connection between the provider and the storage system
a|
`*smis add _storage_sys storage_sys_user_*`
a|
The command waits for up to 15 minutes for the provider to update the cache and respond.
a|
Add a storage system with an HTTPS connection between the provider and the storage system
a|
`*smis addsecure _storage_sys storage_sys_user_*`
a|
The command waits for up to 15 minutes for the provider to update the cache and respond.
a|
List NFS and CIFS exports for a storage system
a|
`*smis exports*`
a|
None
a|
List the storage systems for the CIMOM repository
a|
`*smis list*`
a|
You can run this command to verify the storage systems in the CIMOM repository before adding or deleting storage systems.
a|
List exported LUNs for a storage system
a|
`*smis luns*`
a|
None
a|
Delete a storage system from the CIMOM repository
a|
`*smis delete _storage_sys_*`
a|
If you no longer need to manage a storage system, you can delete it from the CIMOM repository.

Because SMI-S Provider gathers information from all storage systems in the CIMOM repository, you should delete an unused storage system from the repository to maintain optimal performance.
a|
List the current CIM server configuration information
a|
`*smis config show*`
a|
None
a|
List the FC and iSCSI port information for storage system
a|
`*smis initiators*`
a|
None
a|
List the storage pools for storage system
a|
`*smis pools*`
a|
None
a|
List the traditional and flexible volumes for storage system
a|
`*smis volumes*`
a|
None
|===
