---
permalink: task_managing_the_cim_server.html
sidebar: sidebar
keywords: 
summary: 'You can use SMI-S Provider to start, stop, and restart the CIM server and to review its status.'
---
= Managing the CIM server
:icons: font
:imagesdir: ./media/

[.lead]
You can use SMI-S Provider to start, stop, and restart the CIM server and to review its status.

== Before you begin

* You must already have login credentials as Administrator.
* You must already have logged in to the host system as Administrator.

== Steps

. Access NetApp SMI-S Provider.
. Complete one of the following actions:
+
|===
| Action| Command| Additional information
a|
Start the CIM server
a|
`smis cimserver start`
a|
After entering the command, a status message appears every three minutes. If an attempt to reach the CIM server fails, five more attempts are made to contact the server.
a|
Stop the CIM server
a|
`smis cimserver stop`
a|
NA
a|
Restart the CIM server
a|
`smis cimserver restart`
a|
NA
a|
View the CIM server status
a|
`smis cimserver status`
a|
NA
|===

*Related information*

xref:reference_smis_cimserver.adoc[smis cimserver]
