---
permalink: task_managing_storage_systems.html
sidebar: sidebar
keywords: 
summary: 'You can use NetApp SMI-S Provider commands to add, delete, and list storage systems in the CIMOM repository. You can also list NFS and CIFS exports and exported LUNs for storage systems.'
---
= Managing storage systems
:icons: font
:imagesdir: ./media/

[.lead]
You can use NetApp SMI-S Provider commands to add, delete, and list storage systems in the CIMOM repository. You can also list NFS and CIFS exports and exported LUNs for storage systems.

== Before you begin

* You must already have login credentials as Administrator.
* You must already have logged in to the host system as Administrator.

== About this task

For ONTAP, you must specify a management IP address for an SVM, not a cluster IP address, and you must provide the credentials for a vsadmin user. SMI-S Provider does not support cluster IP addresses or node management IP addresses, nor does it support node admin or node SVMs.

[NOTE]
====
You should set the data protocol value to `none` for the management LIF when you add it to the SMI-S Provider.
====

== Steps

. Access NetApp SMI-S Provider.
. Complete one of the following actions:
+
|===
| Action| Command| Additional information
a|
Add a storage system with an HTTP connection between the provider and the storage system
a|
`smis add storage_sys storage_sys_user`
a|
The command waits for up to 15 minutes for the provider to update the cache and respond.
a|
Add a storage system with an HTTPS connection between the provider and the storage system
a|
`smis addsecure storage_sys storage_sys_user`
a|
The command waits for up to 15 minutes for the provider to update the cache and respond.
a|
List NFS and CIFS exports for a storage system
a|
`smis exports`
a|
None
a|
List the storage systems for the CIMOM repository
a|
`smis list`
a|
You can run this command to verify the storage systems in the CIMOM repository before adding or deleting storage systems.
a|
List exported LUNs for a storage system
a|
`smis luns`
a|
None
a|
Delete a storage system from the CIMOM repository
a|
`smis delete storage_sys`
a|
    If you no longer need to manage a storage system, you can delete it from the CIMOM repository.
+
Because SMI-S Provider gathers information from all storage systems in the CIMOM repository, you should delete an unused storage system from the repository to maintain optimal performance.
a|
List the current CIM server configuration information
a|
`smis config show`
a|
None
a|
List the FC and iSCSI port information for storage system
a|
`smis initiators`
a|
None
a|
List the storage pools for storage system
a|
`smis pools`
a|
None
a|
List the traditional and flexible volumes for storage system
a|
`smis volumes`
a|
None
|===

*Related information*

xref:reference_smis_add.adoc[smis add]

xref:reference_smis_addsecure.adoc[smis addsecure]

xref:reference_smis_exports.adoc[smis exports]

xref:reference_smis_list.adoc[smis list]

xref:reference_smis_luns.adoc[smis luns]

xref:reference_smis_delete.adoc[smis delete]

xref:reference_smis_config_show.adoc[smis config show]

xref:reference_smis_initiators.adoc[smis initiators]

xref:reference_smis_pools.adoc[smis pools]

xref:reference_smis_volumes.adoc[smis volumes]

xref:reference_entering_passwords_containing_special_characters.adoc[Issue entering passwords containing special characters]
