---
permalink: task_enabling_or_disabling_audit_logging_for_smi_s_commands.html
sidebar: sidebar
keywords: incoming smi-s command, record, log files, auditor, wbem client
summary: "All incoming SMI-S commands are recorded in audit log files, which enables auditors to track activities of WBEM client operations and provider use. You can enable or disable the logging of these incoming commands by setting a dynamic configuration property."
---
= Enabling or disabling audit logging for SMI-S commands
:icons: font
:imagesdir: ./media/

[.lead]
All incoming SMI-S commands are recorded in audit log files, which enables auditors to track activities of WBEM client operations and provider use. You can enable or disable the logging of these incoming commands by setting a dynamic configuration property.

== What you'll need

* You must already have login credentials as Administrator.
* You must already have logged in to the host system as Administrator.

== About this task

Audit log data can provide a record of access, activity, and configuration change for a CIM server. The contents of the audit file include what command was issued, by whom the command was issued, and what time the command was issued.

The dynamic configuration property `enableAuditLog` enables or disables audit logging at run time. By default, enableAuditLog is set to true.

The common practice is to leave audit logging enabled.

The audit log file (`cimserver_auditlog`) is stored in the pegasus log directory (`C:\Program Files (x86)\Netapp\smis\pegasus\logs`).

The maximum size of the audit log file is 10 MB. After reaching the maximum limit, the file is renamed `cimserver_auditlog.0`, and a new `cimserver auditlog` file is created to collect the newer audit logging information.

NetApp SMI-S Provider maintains the six most recent audit log files: `cimserver_auditlog.0` through `cimserver_auditlog.5`.

== Steps

. Access NetApp SMI-S Provider.
. Set the audit logging of SMI-S commands at runtime:
+
[cols="2*",options="header"]
|===
| Action| Command
a|
*Enable SMI-S audit logging*
a|
`*cimconfig -s enableAuditLog=true*`
a|
*Disable SMI-S audit logging*
a|
`*cimconfig -s enableAuditLog=false*`
|===
