---
permalink: task_verifying_that_the_storage_system_is_working_correctly.html
sidebar: sidebar
keywords: smi-s provider, configure, least storage, cimom repository storage, working, correctly
summary: "Before SMI-S Provider can be configured, you must add at least one storage system to the CIMOM repository, and then verify that the storage system is working correctly."
---
= Verifying that the storage system is working correctly
:icons: font
:imagesdir: ./media/

[.lead]
Before SMI-S Provider can be configured, you must add at least one storage system to the CIMOM repository, and then verify that the storage system is working correctly.

== Before you begin

* You must already have logged in as Administrator.
* You must already have accessed SMI-S Provider.

== Steps

. Add at least one storage system to the CIMOM repository:
+
[cols="2*",options="header"]
|===
| To add a storage system with an...| Enter this command...
a|
HTTP connection between the provider and the storage system
a|
`*smis add _storage_sys storage_sys_user_*`
a|
HTTPS connection between the provider and the storage system
a|
`*smis addsecure _storage_sys storage_sys_user_*`
|===
The command waits for up to 15 minutes for the provider to update the cache and respond.

. Verify the output for the following commands:
+
[cols="2*",options="header"]
|===
| For this command...| Verify that...
a|
`smis list`
a|
The number of items matches the number of storage systems being managed.
a|
`smis disks`
a|
The number of disks matches the total number of disks on all storage systems.
a|
`smis luns`
a|
The number of LUNs matches the total number of LUNs on all storage systems.
a|
`smis pools`
a|
The number of ONTAP_ConcretePools matches the total number of aggregates on all storage systems.
a|
`smis volumes`
a|
The number of volumes matches the total number of volumes on all storage systems.
|===
