---
permalink: task_specifying_trace_file_size.html
sidebar: sidebar
keywords: 
summary: 'If tracing is enabled, the maximum trace file size is 100 MB by default. You can increase or decrease the maximum trace file size by setting the environment variable PEGASUS_TRACE_FILE_SIZE. The value of the trace file size can be 10 MB through 2 GB.'
---
= Specifying trace file size
:icons: font
:imagesdir: ./media/

[.lead]
If tracing is enabled, the maximum trace file size is 100 MB by default. You can increase or decrease the maximum trace file size by setting the environment variable `PEGASUS_TRACE_FILE_SIZE`. The value of the trace file size can be 10 MB through 2 GB.

== Before you begin

* You must already have login credentials as Administrator.
* You must already have logged in to the host system as Administrator.

== Steps

. Access NetApp SMI-S Provider.
. Create a system or user environment variable named `PEGASUS_TRACE_FILE_SIZE` with the new trace file size in bytes.
+
_Windows documentation_ has more information about creating environment variables.

. Restart the CIM server: `smis cimserver restart`

*Related information*

xref:reference_trace_setting_values.adoc[Trace setting values]

xref:task_specifying_trace_settings.adoc[Specifying trace settings]

xref:task_specifying_the_number_of_trace_files_saved.adoc[Specifying the number of trace files saved]
