---
permalink: task-configure-log-settings.html
sidebar: sidebar
keywords: system message, directory, netapp si-s provider, cim server log
summary: "By default, all system messages are logged. In addition, by default, the system message logs are located in the logs directory in the directory in which NetApp SMI-S Provider is installed. You can change the location of and the level of system messages that are written to the CIM server log. For example, you can choose to have logs stored in a directory that you specify and have only fatal system messages written to the CIM server log."
---
= Configure log settings
:icons: font
:imagesdir: ./media/

[.lead]
By default, all system messages are logged. In addition, by default, the system message logs are located in the `logs` directory in the directory in which NetApp SMI-S Provider is installed. You can change the location of and the level of system messages that are written to the CIM server log. For example, you can choose to have logs stored in a directory that you specify and have only fatal system messages written to the CIM server log.

== Before you begin

* You must already have login credentials as Administrator.
* You must already have logged in to the host system as Administrator.

== Steps

. Access NetApp SMI-S Provider.
. Complete one of the following actions:
+
[cols="3*",options="header"]
|===
| Action| Command| Additional information
a|
Change the system message logging level
a|
`*cimconfig -s logLevel=_new_log_level_ -p*`
a|
If you wanted to change the logging level to "`INFORMATION`", for example, you would input this command:
 +
 `*cimconfig -s logLevel=INFORMATION -p*`
a|
Change the system message log directory
a|
`*cimconfig -s logdir=new_log_directory -p*` If the `_new_log_directory_` contains space, you must enclose it in quotation marks (`"_new log directory_"`).
a|
If you wanted to change the log directory to "`serverlogs`", for example, you would input this command:

`*cimconfig -s logdir=serverlogs -p*`
|===

. Restart the CIM server:
+
`*smis cimserver restart*`
