---
permalink: task_managing_cimom_configuration_settings.html
sidebar: sidebar
keywords: 
summary: 'You can use SMI-S Provider to manage the CIMOM configuration, such as enabling or disabling HTTP and HTTPS connections and changing HTTP and HTTPS port numbers. By default, HTTP connections are enabled, allowing clients to connect to the CIM server without using SSL encryption.'
---
= Managing CIMOM configuration settings
:icons: font
:imagesdir: ./media/

[.lead]
You can use SMI-S Provider to manage the CIMOM configuration, such as enabling or disabling HTTP and HTTPS connections and changing HTTP and HTTPS port numbers. By default, HTTP connections are enabled, allowing clients to connect to the CIM server without using SSL encryption.

== Before you begin

* You must already have login credentials as Administrator.
* You must already have logged in to the host system as Administrator.

== About this task

If your environment requires encrypted traffic to and from the CIM server, you must first disable HTTP connections and then verify that HTTPS connections for the CIM server are enabled.

== Steps

. Access NetApp SMI-S Provider.
. Complete one of the following actions:
+
|===
| Action| Command| Additional information
a|
Enable the HTTP connection
a|
`cimconfig -s enableHttpConnection=true -p`
a|
NA
a|
Disable the HTTP connection
a|
`cimconfig -s enableHttpConnection=false -p`
a|
NA
a|
Enable the HTTPS connection
a|
`cimconfig -s enableHttpsConnection=true -p`
a|
NA
a|
Disable the HTTPS connection
a|
`cimconfig -s enableHttpsConnection=false -p`
a|
NA
a|
Modify the HTTP port number
a|
`cimconfig -s httpPort=new_port_number -p`
a|
By default, the HTTP port number is 5988. If you wanted to change it to 5555, for example, you would input this command: `cimconfig -s httpPort=5555 -p`
a|
Modify the HTTPS port number
a|
`cimconfig -s httpsPort=new_port_number -p`
a|
By default, the HTTP port number is 5989. If you wanted to change it to 5556, for example, you would input this command: `cimconfig -s httpsPort=5556 -p`
|===

. Restart the CIM server: `smis cimserver restart`

*Related information*

xref:reference_cimconfig_command_options.adoc[cimconfig]
